/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef CGPACKAGEMANAGER_AUTODEFS_H
#define CGPACKAGEMANAGER_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_CGPACKAGEMANAGER_NAME "CGPackageManager"
#define S3E_EXT_CGPACKAGEMANAGER_HASH 0x1fe82d56

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("CGPackageManager", 1)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !CGPACKAGEMANAGER_AUTODEFS_H */
