/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "CGPackageManager_autodefs.h"
#include "s3eEdk.h"
#include "CGPackageManager.h"
//Declarations of Init and Term functions
extern s3eResult CGPackageManagerInit();
extern void CGPackageManagerTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static const char* getInstallerPackageName_wrap()
{
    IwTrace(CGPACKAGEMANAGER_VERBOSE, ("calling CGPackageManager func on main thread: getInstallerPackageName"));
    return (const char*)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)getInstallerPackageName, 0);
}

#define getInstallerPackageName getInstallerPackageName_wrap


#endif

void CGPackageManagerRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[1];
    funcPtrs[0] = (void*)getInstallerPackageName;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[1] = { 0 };

    /*
     * Register the extension
     */
s3eEdkRegister("CGPackageManager", funcPtrs, sizeof(funcPtrs), flags, CGPackageManagerInit, CGPackageManagerTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int CGPackageManagerStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&CGPackageManagerRegisterExt;
    return 0;
}

int g_CGPackageManagerVal = CGPackageManagerStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    CGPackageManagerRegisterExt();
}
#endif

#endif
